services:
  database:
    image: mysql
    platform: linux/x86_64
    container_name: twitter_api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'twitter_api'
    ports:
      - '3306:3306'
